name: client
description: "RecEnc"
publish_to: "Github.com/JojoSlice/RecEng"
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  flutter_secure_storage: ^10.0.0
  flutter_neumorphic_plus: ^3.3.3
  google_fonts: ^8.0.2
  video_player: ^2.9.2
  image_picker: ^1.2.1
  video_compress: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
