<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-analytics_service-e68f68d2-7ca3-431e-94e3-2b1a65982f4d</UserSecretsId>
    <RootNamespace>analytics_service</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit.RabbitMQ" Version="9.0.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.4" />
    <PackageReference Include="Npgsql" Version="10.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RecEng.Contracts\RecEng.Contracts.csproj" />
  </ItemGroup>
</Project>
